### ISSUE TITLE
hstshijack exit code 4

### ISSUE THREAD

**Issue by seyo-IV** [bettercap/caplets#53]
running hstshinject generates an error. Couldn't find anything about this error.
 
### Environment
* Version 2.23.
* Kali Linux 3.10.73,  aarch64.
* Command line: bettercap -iface wlan0.
* hstshijack/tshshijack.
### Steps to Reproduce
1. hstshijack/hstshijack

**Expected behavior: caplet run successfully

**Actual behavior: [sys.log] [err] exit status 4

**Comment by BlackLottusBR** [comment]
/hstshijack != tshshijack. Be careful with name

**Comment by buffermet** [comment]
You need to write a complete report.

**Comment by mrsheepsheep** [comment]
Re-opening this old issue because I'm encountering the same exit status code.

The issue doesn't seem to be the `hstshijack` module on its own, but rather all proxy-related commands, so my guess is that something is wrong with iptables or something related to networking / firewall.

### Environment

* bettercap v2.32.0
* linux arm64
* go1.15.15
* Running on Kali Nethunter (Android 10, rooted device, running directly from kali chroot)
 * I'm also using Bettercap on a Kali VM, but I never had an issue with the proxy modules.

Bettercap started with `bettercap -i wlan0` followed by `http.proxy on`.
Same error when running `https.proxy on` and `any.proxy on`

Debug output below, but there are no debug messages related the proxy.

![image](https://user-images.githubusercontent.com/4931825/132121789-47f7378f-1d03-49f3-8763-2c9d08cc4fbd.png)

`curl` exits with status code 7 when connection fails, so that was expected.

**Expected behavior:**
Proxy should start running and listen for connections on specified port (in the case of the screenshort, port 8081)

**Actual behavior:**
`http.proxy on` and other proxy-related services exits with status code 4, redirection is marked as already enabled, but running `curl 127.0.0.1:8081` to reach the proxy shows it's not running.

In comparison, here is how it behaves on a "normal" Kali amd64 installation :

![image](https://user-images.githubusercontent.com/4931825/132121862-56ed9d1c-87e0-4c70-8d7e-37eef0175ed2.png)

I have no idea what's wrong here, but I guess it's definetely related to the environment (Nethunter, Android...).
Any suggestion on how I could further debug this ?
